### PR TITLE
Feature/1674 event server

### PR DESCRIPTION
**Pull request by lewisdaly**

### CODE REVIEW

**Comment by kleyow** [comment]
Just a heads up, I'm unable to start the adapter.
```
[kleyow@lavi thirdparty-api-adapter] (feature/1674-event-server) npm run start

> @mojaloop/thirdparty-api-adapter@11.4.0 start /home/kleyow/mojaloop/thirdparty-api-adapter
> ts-node -r tsconfig-paths/register -P ./tsconfig.json ./src/cli.ts

2020-09-09T19:22:42.482Z - info: thirdparty-api-adapter is running @ http://0.0.0.0:3008
2020-09-09T19:22:42.483Z - info: participantEndpointCache::initializeCache::start::clientOptions - {"partition":"endpoint-cache"}
2020-09-09T19:22:42.483Z - info: participantEndpointCache::initializeCache::start::policyOptions - {"expiresIn":180000,"generateTimeout":30000}
2020-09-09T19:22:42.483Z - info: participantEndpointCache::initializeCache::Cache initialized successfully
http://0.0.0.0:3008
method  path      description
------  --------  -----------
GET     /{path*}             
POST    /{path*}             
PUT     /{path*}             
DELETE  /{path*}             

2020-09-09T19:23:12.205Z - error: Consumer::onError()[topics='topic-notification-event'] - Error: Local: Broker transport failure)
2020-09-09T19:23:12.205Z - error: Consumer::onError()[topics='topic-notification-event'] - Error: Local: All broker connections are down)
2020-09-09T19:23:12.206Z - error: Consumer::onError()[topics='topic-notification-event'] - Error: Local: Broker transport failure
    at Function.createLibrdkafkaError [as create] (/home/kleyow/mojaloop/thirdparty-api-adapter/node_modules/node-rdkafka/lib/error.js:411:10)
    at /home/kleyow/mojaloop/thirdparty-api-adapter/node_modules/node-rdkafka/lib/client.js:350:28)
2020-09-09T19:23:12.206Z - error: broker transport failure
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @mojaloop/thirdparty-api-adapter@11.4.0 start: `ts-node -r tsconfig-paths/register -P ./tsconfig.json ./src/cli.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @mojaloop/thirdparty-api-adapter@11.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kleyow/.npm/_logs/2020-09-09T19_23_12_218Z-debug.log
```

I'm not experienced enough to diagnose kafka.

**Comment by lewisdaly** [comment]
> I'm not experienced enough to diagnose kafka.

Sorry, forgot to mention that bit. You just need to start `central-ledger` from our `pisp/docker-local` setup, and that will bring up kafka and the topics we need.

More info: https://github.com/mojaloop/thirdparty-api-adapter/tree/feature/1674-event-server/docs#kafkacat-notes

**Comment by lewisdaly** [comment]
Closing for now

**Comment by kleyow** [comment]
That makes sense, thanks for clarifying.

I have the domain function ready and prepped off a branch of this branch. Just needed to get it running so I can test it with kafkacat.

**Comment by lewisdaly** [comment]
Follow up PR: https://github.com/mojaloop/thirdparty-api-adapter/pull/25/

**Pull request closed without merging**
